### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by canabina**

### CODE REVIEW

**Comment by canabina** [comment]
-

**Comment by ghaiklor** [comment]
@canabina can you describe what this PR fixes ? Is it about JWT token which doesn't takes from Header?

**Comment by canabina** [comment]
Yes, this pr fix problem about extract authScheme name in Header

**Comment by ghaiklor** [comment]
@canabina published under [v1.3.7](https://github.com/ghaiklor/generator-sails-rest-api/releases/tag/v1.3.7). Thanks for contribution.

**Pull request merged**
