### PR TITLE
feature(app): added esdoc for code documentation

### PR DESCRIPTION
**Pull request by BraunreutherA**
Added Esdoc for code documentation. It uses the same syntax as jsdocs but is compatible with es6

### CODE REVIEW

**Comment by ghaiklor** [comment]
@BraunreutherA is that API documentation or code documentation ?

**Comment by BraunreutherA** [comment]
It's code documentation it generates nice html files from your annotations

**Comment by BraunreutherA** [comment]
just run npm run docs and see :)

**Comment by ghaiklor** [comment]
I noticed that yours commit is starts from `feature(app)`, but we have a little different specs here. This repository commitizen-friendly, so you can use `git cz` command.

The problem here is `semantic-release` can't parse commits and generate changelog. So you just need to use `feat()` but not `feature()` :smile_cat:

**Comment by BraunreutherA** [comment]
ah okay, thank you didn't know that command :+1:

**Comment by ghaiklor** [comment]
@BraunreutherA http://commitizen.github.io/cz-cli/

**Pull request merged**
